// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttsfulgsmhhynxvjtnpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0c2Z1bGdzbWhoeW54dmp0bnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTQyNDQsImV4cCI6MjA3NDI5MDI0NH0.pANzbGSwbpuHniZN9zCXd9aP9DIK1_mJkSfT6e5A3yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});